In [ ]:
# Solutions of Task 1


In [3]:
# Task 1.1

nums = [3, 5, 7, 8, 12]

nums = [x**3 for x in nums]
nums


[27, 125, 343, 512, 1728]

In [7]:
# Task 1.2

anml_legs = dict()
animals, legs = ['parrot', 'goat', 'spider', 'crab'], [2, 4, 8, 10]

anml_legs = dict(zip(animals, legs))
anml_legs

{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}

In [15]:
# Task 1.3

import sys
stdout = sys.stdout

anml_legs = {'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}
count = 0

for _ in anml_legs.items():
    print(f'{_[0]} has {_[1]} legs')
    count += _[1]
print(f'Number of Total legs is: {count}')

parrot has 2 legs
goat has 4 legs
spider has 8 legs
crab has 10 legs
Number of Total legs is: 24


In [19]:
# Task 1.4

A = (3, 9, 4, [5, 6])
A[-1][0] = 8
print(A)


(3, 9, 4, [8, 6])


In [23]:
# Task 1.5

A = (1, 2, 3, 4)
del A

In [25]:
# Task 1.6

B = ('a', 'p', 'p', 'l', 'e')
print(f'"p" occurred {B.count("p")} times')

"p" occurred 2 times


In [27]:
# Task 1.7

B = ('a', 'p', 'p', 'l', 'e')
print(f'the index of "l" in B is: {B.index("l")}')

the index of "l" in B is: 3


In [ ]:
# Solutions of Task 2

In [29]:
# Task 2.1

import numpy as np
A = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

A_np = np.array(A)
A_np

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# Task 2.2
b = A_np[0:2, 0:2]
b

array([[1, 2],
       [5, 6]])

In [35]:
# Task 2.3

C = np.zeros_like(A)
print(C)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [37]:
# Task 2.4

z = np.array([1, 2, 3])

for col in range(A_np.shape[1]):
    C[:, col] = A_np[:, col] + z
C

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [39]:
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
v = np.array([9,10])

# Task 2.5
X_add_Y = np.add(X, Y)
print(f'X + Y = {X_add_Y}\n')

# Task 2.6
X_mul_Y = np.multiply(X, Y)
print(f'X x Y = {X_mul_Y}\n')

# Task 2.7
sqrt_Y = np.sqrt(Y)
print(f'sq. root of Y = {sqrt_Y}\n')

# Task 2.8
dot_prod = np.dot(X, v)
print(f'Dot product of X and v = {dot_prod}\n')

# Task 2.9
x_sum_columns = np.sum(X, axis=0)
print(f'sum of columns of X = {x_sum_columns}\n')


X + Y = [[ 6  8]
 [10 12]]

X x Y = [[ 5 12]
 [21 32]]

sq. root of Y = [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]

Dot product of X and v = [29 67]

sum of columns of X = [4 6]



In [ ]:
# Solutions of Task 3

In [43]:
# Task 3.1
def compute(distance, time):
    velocity = distance/time
    print(f"Velocity = {velocity:.3f}")
    return
compute(distance=120, time=76)

Velocity = 1.579


In [49]:
# Task 3.2
import functools

even_num = [x for x in range(1,13) if x%2 == 0]
print(f'even numbers till 12: {even_num}')

def mul(lst):
    multiple = functools.reduce(lambda x, y: x*y, lst)
    print(f'list items multiple: {multiple}')
    return

mul(even_num)

even numbers till 12: [2, 4, 6, 8, 10, 12]
list items multiple: 46080


In [ ]:
# Solutions of Task 4

In [53]:
import pandas as pd
df = pd.DataFrame([[1,6,7,7], [2,7,9,5], [3,5,8,2], [5,4,6,8], [5,8,5,8]], columns=['C1', 'C2', 'C3', 'C4'])
print(df)

# Task 4.1

print('\nPrinting only first 2 rows of df')
print(df[:2])

   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8

Printing only first 2 rows of df
   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [69]:
# Task 4.2

print('\nPrinting first 2 columns of df')
print(df.iloc[:, 1:2])


Printing first 2 columns of df
   C2
0   6
1   7
2   5
3   4
4   8


In [87]:
# Task 4.3

df.rename(columns={'C3': 'B3'}, inplace=True)
print('\nPrinting renamed column df')
print(df)


Printing renamed column df
   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [89]:
# Task 4.4
print('\n Adding a new null column[sum] in df')
df['Sum'] = None
print(df)


 Adding a new null column[sum] in df
   C1  C2  B3  C4   Sum
0   1   6   7   7  None
1   2   7   9   5  None
2   3   5   8   2  None
3   5   4   6   8  None
4   5   8   5   8  None


In [91]:
# Task 4.5

print('\nTaking Sum in sum column')
sums = df.sum(axis=1)
df['Sum'] = sums
print(df)


Taking Sum in sum column
   C1  C2  B3  C4 Sum
0   1   6   7   7  21
1   2   7   9   5  23
2   3   5   8   2  18
3   5   4   6   8  23
4   5   8   5   8  26


In [109]:
# Task 4.6

# Read the dataframe file
dataframe = pd.read_csv("C:/Users/dell/hello_sample.csv")

# Task 4.7
print(dataframe)

    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


In [107]:
# Task 4.8

print(f'Printing last 2 rows of dataframe\n {dataframe.tail(2)}')

Printing last 2 rows of dataframe
    Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [111]:
# Task 4.9

print(f'\nPrinting dataframe info: \n')
dataframe.info()


Printing dataframe info: 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 868.0+ bytes


In [113]:
# Task 4.10

print(f'\nPrinting shape of dataframe: {dataframe.shape}')


Printing shape of dataframe: (23, 4)


In [139]:
# Task 4.11

# Decending Order
sorted_dataframe_desc = dataframe.sort_values(by='Weight', ascending=False)
print(sorted_dataframe_desc)

# Ascending Orders
sorted_dataframe = dataframe.sort_values(by='Weight')
print(sorted_dataframe)

    Gender  F_Color     B_Month  Weight
5   Female    Black    december      97
15    Male   Yellow   November       90
14    Male    Green    January       90
12    Male    Green    December      85
17    Male    Black     January      82
4     Male    black    October       80
0     Male    Black       March      77
19  Female    Black    October       76
21    Male   Yellow       April      74
13    Male    Black       April      72
1     Male      Red       March      72
20    Male    Black   February       67
22    Male      Red  September       66
11    Male    Black   September      65
3   Female     Blue    February      63
10  Female      Red    October       60
8     Male     Blue        July      60
18    Male  Mustard   December       60
6     Male   Orange      August      60
7   Female      Red   September      59
9     Male     Blue         May      58
16    Male    Black      August      54
2     Male    Black     October      53
    Gender  F_Color     B_Month  Weight


In [125]:
# Task 4.12 (a)

null_check = dataframe.isnull()

print(null_check)


    Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False


In [133]:
# Task 4.12 (b)

cleaned_dataframe = dataframe.dropna()

print(cleaned_dataframe)

    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66
